-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: components/mwstake-mediawiki-component-commonwebapis/sql/mws_user_index.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE mws_user_index (
  mui_user_id INT NOT NULL,
  mui_user_name TEXT NOT NULL,
  mui_user_real_name TEXT NOT NULL,
  PRIMARY KEY(mui_user_id)
);
