-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: components/mwstake-mediawiki-component-commonwebapis/sql/mws_category_index.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE mws_category_index (
  mci_cat_id INT NOT NULL, mci_title TEXT NOT NULL,
  mci_page_title TEXT DEFAULT '' NOT NULL,
  mci_count INT DEFAULT 0 NOT NULL
);
