-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: components/mwstake-mediawiki-component-commonwebapis/sql/mws_title_index.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE mws_title_index (
  mti_page_id INT NOT NULL,
  mti_namespace INT NOT NULL,
  mti_title TEXT NOT NULL,
  mti_displaytitle TEXT NOT NULL,
  PRIMARY KEY(mti_page_id)
);
