-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/mws_title_index_local_fields_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE mws_title_index
  ADD mti_db_key TEXT NOT NULL;
ALTER TABLE mws_title_index
  ADD mti_page_lang TEXT NOT NULL;
ALTER TABLE mws_title_index
  ADD mti_content_model TEXT NOT NULL;
