-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: vendor/mwstake/mediawiki-component-commonwebapis/sql/mws_title_index_full.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE mws_title_index_full (
  mti_page_id INT NOT NULL,
  mti_wiki_id TEXT NOT NULL,
  mti_namespace INT NOT NULL,
  mti_title TEXT NOT NULL,
  mti_displaytitle TEXT NOT NULL,
  mti_dbkey TEXT NOT NULL,
  mti_content_model TEXT NOT NULL,
  mti_prefixed TEXT NOT NULL,
  mti_namespace_text TEXT NOT NULL,
  PRIMARY KEY(mti_page_id, mti_wiki_id)
);
