-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/mws_title_index_leafpage_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE mws_title_index
  ADD mti_leaf_title TEXT NOT NULL;

CREATE INDEX mws_title_index_title_index ON mws_title_index (mti_title);

CREATE INDEX mws_title_index_displaytitle_index ON mws_title_index (mti_displaytitle);

CREATE INDEX mws_title_index_leaftitle_index ON mws_title_index (mti_leaf_title);
