-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/mws_title_index_wiki_id_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE mws_title_index
  DROP CONSTRAINT mws_title_index_pkey;
ALTER TABLE mws_title_index
  ADD mti_wiki_id TEXT DEFAULT '' NOT NULL;
ALTER TABLE mws_title_index
  ADD PRIMARY KEY (mti_page_id, mti_wiki_id);
