-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: components/mwstake-mediawiki-component-commonwebapis/sql/mws_category_index_patch_page_title.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE mws_category_index
  DROP CONSTRAINT mws_category_index_pkey;
ALTER TABLE mws_category_index
  ADD mci_page_title TEXT DEFAULT '' NOT NULL;
