-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/mws_title_index_first_letter_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE mws_title_index
  ADD mti_first_letter TEXT NOT NULL DEFAULT '';

CREATE INDEX mws_title_index_first_letter_index ON mws_title_index (mti_first_letter, mti_namespace);
