-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/mws_title_index_leafpage_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__mws_title_index AS
SELECT
  mti_page_id,
  mti_namespace,
  mti_title,
  mti_displaytitle
FROM /*_*/mws_title_index;
DROP TABLE /*_*/mws_title_index;


CREATE TABLE /*_*/mws_title_index (
    mti_page_id INTEGER UNSIGNED NOT NULL,
    mti_namespace INTEGER UNSIGNED NOT NULL,
    mti_title BLOB NOT NULL,
    mti_displaytitle BLOB NOT NULL,
    mti_leaf_title BLOB NOT NULL,
    PRIMARY KEY(mti_page_id)
  );
INSERT INTO /*_*/mws_title_index (
    mti_page_id, mti_namespace, mti_title,
    mti_displaytitle
  )
SELECT
  mti_page_id,
  mti_namespace,
  mti_title,
  mti_displaytitle
FROM
  /*_*/__temp__mws_title_index;
DROP TABLE /*_*/__temp__mws_title_index;

CREATE INDEX mws_title_index_title_index ON /*_*/mws_title_index (mti_title);

CREATE INDEX mws_title_index_displaytitle_index ON /*_*/mws_title_index (mti_displaytitle);

CREATE INDEX mws_title_index_leaftitle_index ON /*_*/mws_title_index (mti_leaf_title);
