-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: components/mwstake-mediawiki-component-commonwebapis/sql/mws_category_index_patch_page_title.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__mws_category_index AS
SELECT
  mci_cat_id,
  mci_title,
  mci_count
FROM /*_*/mws_category_index;
DROP TABLE /*_*/mws_category_index;


CREATE TABLE /*_*/mws_category_index (
    mci_cat_id INTEGER UNSIGNED NOT NULL,
    mci_title BLOB NOT NULL, mci_count INTEGER UNSIGNED DEFAULT 0 NOT NULL,
    mci_page_title BLOB DEFAULT '' NOT NULL
  );
INSERT INTO /*_*/mws_category_index (mci_cat_id, mci_title, mci_count)
SELECT
  mci_cat_id,
  mci_title,
  mci_count
FROM
  /*_*/__temp__mws_category_index;
DROP TABLE /*_*/__temp__mws_category_index;
