-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: vendor/mwstake/mediawiki-component-commonwebapis/sql/mws_title_index_full.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/mws_title_index_full (
  mti_page_id INTEGER UNSIGNED NOT NULL,
  mti_wiki_id BLOB NOT NULL,
  mti_namespace INTEGER UNSIGNED NOT NULL,
  mti_title BLOB NOT NULL,
  mti_displaytitle BLOB NOT NULL,
  mti_dbkey BLOB NOT NULL,
  mti_content_model BLOB NOT NULL,
  mti_prefixed BLOB NOT NULL,
  mti_namespace_text BLOB NOT NULL,
  PRIMARY KEY(mti_page_id, mti_wiki_id)
);
