-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: components/mwstake-mediawiki-component-commonwebapis/sql/mws_title_index_displaytitle_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/mws_title_index
  ADD COLUMN mti_displaytitle BLOB NOT NULL;
