-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/mws_title_index_local_fields_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/mws_title_index
  ADD COLUMN mti_db_key BLOB NOT NULL;
ALTER TABLE /*_*/mws_title_index
  ADD COLUMN mti_page_lang BLOB NOT NULL;
ALTER TABLE /*_*/mws_title_index
  ADD COLUMN mti_content_model BLOB NOT NULL;
