-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: components/mwstake-mediawiki-component-commonwebapis/sql/mws_title_index.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/mws_title_index (
  mti_page_id INT UNSIGNED NOT NULL,
  mti_namespace INT UNSIGNED NOT NULL,
  mti_title VARBINARY(255) NOT NULL,
  mti_displaytitle VARBINARY(255) NOT NULL,
  PRIMARY KEY(mti_page_id)
) /*$wgDBTableOptions*/;
