-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/mws_title_index_wiki_id_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX `primary` ON /*_*/mws_title_index;
ALTER TABLE /*_*/mws_title_index
  ADD mti_wiki_id VARBINARY(255) DEFAULT '' NOT NULL;
ALTER TABLE /*_*/mws_title_index
  ADD PRIMARY KEY (mti_page_id, mti_wiki_id);
