-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: components/mwstake-mediawiki-component-commonwebapis/sql/mws_user_index.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/mws_user_index (
  mui_user_id INT UNSIGNED NOT NULL,
  mui_user_name VARBINARY(255) NOT NULL,
  mui_user_real_name VARBINARY(255) NOT NULL,
  PRIMARY KEY(mui_user_id)
) /*$wgDBTableOptions*/;
