-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: vendor/mwstake/mediawiki-component-commonwebapis/sql/mws_title_index_full.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/mws_title_index_full (
  mti_page_id INT UNSIGNED NOT NULL,
  mti_wiki_id VARBINARY(255) NOT NULL,
  mti_namespace INT UNSIGNED NOT NULL,
  mti_title VARBINARY(255) NOT NULL,
  mti_displaytitle VARBINARY(255) NOT NULL,
  mti_dbkey VARBINARY(255) NOT NULL,
  mti_content_model VARBINARY(255) NOT NULL,
  mti_prefixed VARBINARY(255) NOT NULL,
  mti_namespace_text VARBINARY(255) NOT NULL,
  PRIMARY KEY(mti_page_id, mti_wiki_id)
) /*$wgDBTableOptions*/;
